2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] MongoDB starting : pid=15199 port=27017 dbpath=/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/ 64-bit host=simonx
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] db version v3.4.4
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] git version: 888390515874a9debd1b6c5d36559ca86b44babd
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] allocator: tcmalloc
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] modules: none
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] build environment:
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten]     distmod: ubuntu1404
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten]     distarch: x86_64
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten]     target_arch: x86_64
2017-04-22T20:44:44.309+0200 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, storage: { dbPath: "datadir/" }, systemLog: { destination: "file", path: "logfile" } }
2017-04-22T20:44:44.330+0200 I -        [initandlisten] Detected data files in /home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/ created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-04-22T20:44:44.330+0200 I STORAGE  [initandlisten] 
2017-04-22T20:44:44.330+0200 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-04-22T20:44:44.330+0200 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-04-22T20:44:44.330+0200 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=11495M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] 
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] 
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] 
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] 
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-04-22T20:44:44.587+0200 I CONTROL  [initandlisten] 
2017-04-22T20:44:44.592+0200 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/diagnostic.data'
2017-04-22T20:44:44.593+0200 I NETWORK  [thread1] waiting for connections on port 27017
2017-04-22T20:44:45.090+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54108 #1 (1 connection now open)
2017-04-22T20:44:45.091+0200 I NETWORK  [conn1] received client metadata from 127.0.0.1:54108 conn1: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:44:45.092+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54110 #2 (2 connections now open)
2017-04-22T20:44:45.092+0200 I NETWORK  [conn2] received client metadata from 127.0.0.1:54110 conn2: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:45:39.599+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54112 #3 (3 connections now open)
2017-04-22T20:45:39.599+0200 I NETWORK  [conn3] received client metadata from 127.0.0.1:54112 conn3: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:45:39.600+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54114 #4 (4 connections now open)
2017-04-22T20:45:39.600+0200 I NETWORK  [conn4] received client metadata from 127.0.0.1:54114 conn4: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:45:43.005+0200 I -        [conn3] end connection 127.0.0.1:54112 (4 connections now open)
2017-04-22T20:45:43.005+0200 I -        [conn4] end connection 127.0.0.1:54114 (3 connections now open)
2017-04-22T20:47:07.198+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54120 #5 (3 connections now open)
2017-04-22T20:47:07.198+0200 I NETWORK  [conn5] received client metadata from 127.0.0.1:54120 conn5: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:47:07.199+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54122 #6 (4 connections now open)
2017-04-22T20:47:07.199+0200 I NETWORK  [conn6] received client metadata from 127.0.0.1:54122 conn6: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:47:09.292+0200 I -        [conn6] end connection 127.0.0.1:54122 (4 connections now open)
2017-04-22T20:47:09.292+0200 I -        [conn5] end connection 127.0.0.1:54120 (4 connections now open)
2017-04-22T20:47:26.857+0200 I -        [conn2] end connection 127.0.0.1:54110 (2 connections now open)
2017-04-22T20:47:26.857+0200 I -        [conn1] end connection 127.0.0.1:54108 (2 connections now open)
2017-04-22T20:48:01.211+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54126 #7 (1 connection now open)
2017-04-22T20:48:01.211+0200 I NETWORK  [conn7] received client metadata from 127.0.0.1:54126 conn7: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.4" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "14.04" } }
2017-04-22T20:48:01.213+0200 I COMMAND  [conn7] terminating, shutdown command received
2017-04-22T20:48:01.213+0200 I NETWORK  [conn7] shutdown: going to close listening sockets...
2017-04-22T20:48:01.213+0200 I NETWORK  [conn7] closing listening socket: 7
2017-04-22T20:48:01.213+0200 I NETWORK  [conn7] closing listening socket: 8
2017-04-22T20:48:01.213+0200 I NETWORK  [conn7] removing socket file: /tmp/mongodb-27017.sock
2017-04-22T20:48:01.213+0200 I NETWORK  [conn7] shutdown: going to flush diaglog...
2017-04-22T20:48:01.213+0200 I FTDC     [conn7] Shutting down full-time diagnostic data capture
2017-04-22T20:48:01.217+0200 I STORAGE  [conn7] WiredTigerKVEngine shutting down
2017-04-22T20:48:01.308+0200 I STORAGE  [conn7] shutdown: removing fs lock...
2017-04-22T20:48:01.308+0200 I CONTROL  [conn7] now exiting
2017-04-22T20:48:01.308+0200 I CONTROL  [conn7] shutting down with code:0
